/** Canonical site URL for SEO, sitemaps, and Open Graph. */
export const SITE_URL = "https://alphacomonline.com"

/** All brands for SEO and sitemap (slug used in URL). Deduplicated with canonical casing. */
export const SEO_BRANDS = [
  { name: "Logitech", slug: "Logitech" },
  { name: "Anker", slug: "Anker" },
  { name: "Micropack", slug: "Micropack" },
  { name: "SanDisk", slug: "SanDisk" },
  { name: "Acer", slug: "Acer" },
  { name: "Afox", slug: "Afox" },
  { name: "Aicon", slug: "Aicon" },
  { name: "Airsky", slug: "Airsky" },
  { name: "ALFA", slug: "ALFA" },
  { name: "ALHUA", slug: "ALHUA" },
  { name: "Amazon", slug: "Amazon" },
  { name: "APC", slug: "APC" },
  { name: "Apple", slug: "Apple" },
  { name: "Belkin", slug: "Belkin" },
  { name: "Bluegate", slug: "Bluegate" },
  { name: "Canon", slug: "Canon" },
  { name: "Coolbell", slug: "Coolbell" },
  { name: "D-Link", slug: "D-Link" },
  { name: "Dell", slug: "Dell" },
  { name: "Digirich", slug: "Digirich" },
  { name: "DJI", slug: "DJI" },
  { name: "Epson", slug: "Epson" },
  { name: "Ezashy", slug: "Ezashy" },
  { name: "Flying Fox", slug: "Flying Fox" },
  { name: "Generic", slug: "Generic" },
  { name: "Golden Crown", slug: "Golden Crown" },
  { name: "Greenlion", slug: "Greenlion" },
  { name: "HDMI", slug: "HDMI" },
  { name: "Hiksemi", slug: "Hiksemi" },
  { name: "Hikvision", slug: "Hikvision" },
  { name: "HP", slug: "HP" },
  { name: "Huawei", slug: "Huawei" },
  { name: "JBL", slug: "JBL" },
  { name: "Kaspersky", slug: "Kaspersky" },
  { name: "Kingston", slug: "Kingston" },
  { name: "Ldnio", slug: "Ldnio" },
  { name: "Lenovo", slug: "Lenovo" },
  { name: "Lexar", slug: "Lexar" },
  { name: "LG", slug: "LG" },
  { name: "Maxi", slug: "Maxi" },
  { name: "Microsoft", slug: "Microsoft" },
  { name: "Norton", slug: "Norton" },
  { name: "Olax", slug: "Olax" },
  { name: "Onten", slug: "Onten" },
  { name: "Oscoo", slug: "Oscoo" },
  { name: "Poly", slug: "Poly" },
  { name: "Quick Heal", slug: "Quick Heal" },
  { name: "Remax", slug: "Remax" },
  { name: "Samsung", slug: "Samsung" },
  { name: "Sanyo", slug: "Sanyo" },
  { name: "Seagate", slug: "Seagate" },
  { name: "Smaat", slug: "Smaat" },
  { name: "Sony", slug: "Sony" },
  { name: "TP-Link", slug: "TP-Link" },
  { name: "Transcend", slug: "Transcend" },
  { name: "Veeda", slug: "Veeda" },
  { name: "Vellygood", slug: "Vellygood" },
  { name: "Vivatech", slug: "Vivatech" },
  { name: "Vnzane", slug: "Vnzane" },
  { name: "WD", slug: "WD" },
  { name: "Weifeng", slug: "Weifeng" },
  { name: "Xiaomi", slug: "Xiaomi" },
  { name: "Xprinter", slug: "Xprinter" },
  { name: "Yuteng", slug: "Yuteng" },
] as const
